import Footer from '@/components/Footer'
import '../globals.css'
import Header from '@/components/Header'
import Providers from '@/components/Providers'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import { signIn } from 'next-auth/react'
import Signin from '@/components/Signin'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang='en' className='h-full'>
      <body className='flex h-full flex-col justify-between '>
        <Providers session={session}>
          <Header />
          {JSON.stringify(session, null, 2)}
          {!session && <Signin />}
          <main className='flex-grow px-12 py-6 '>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
